stages:
  - build
  - deploy_server
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy_server:
  stage: deploy_server
  image: php:latest
  services:
    - mysql:latest
  before_script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - apt-get install nodejs -yqq
    - apt-get install npm -yqq
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - composer global require symfony/cli
  script:
    - composer require symfony/webpack-encore-bundle
    - npm install
    - php bin/console doctrine:database:create
    - php bin/console make:migration
    - php bin/console doctrine:migrations:migrate
    - symfony server:start
  only:
    - master

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  only:
    - master
