<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPc4Mzhc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPc4Mzhc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPc4Mzhc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPc4Mzhc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPc4Mzhc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pc4Mzhc',
    'container.build_id' => 'dab189b8',
    'container.build_time' => 1703086871,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPc4Mzhc');
