<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7c8RVz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7c8RVz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7c8RVz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7c8RVz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7c8RVz\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7c8RVz',
    'container.build_id' => '28d1bc66',
    'container.build_time' => 1703231091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7c8RVz');
